### ISSUE TITLE
Md5 hash issue

### ISSUE THREAD

**Issue by fiservedpi** [dorgan/Unraid-networkstats#12]
![Screenshot_20191210-225649](https://user-images.githubusercontent.com/42981853/70590461-c7dba780-1ba0-11ea-851b-181820196295.png)
`Wrong'vnstat-1.18-x86_64-1_slonly.txz' package md5 hash.
plugin: run failed: /bin/bash retval: 1`

**Comment by RomanHelmet** [comment]
I'm getting the exact same issue.

**Comment by fiservedpi** [comment]
Pretty sure the dev is MIA open issue from 1 year ago still open

**Comment by dorgan** [comment]
I am not Mia.  I'll look into it tonight, maybe I need to pull a new
version of the plugin.

**Comment by fiservedpi** [comment]
Sweet!! Nice to see

**Comment by dorgan** [comment]
Sorry for the delay this is now resolved in d70e688e3b90737612940fd073f973560e4034ba

**Comment by fiservedpi** [comment]
Awesome thanks for the hard work
