### ISSUE TITLE
List all interfaces

### ISSUE THREAD

**Issue by erik-helleren** [dorgan/Unraid-networkstats#13]
I really like the plugin, but I would find it even more useful if I could configure it to monitor the virtual docker interfaces.  I have a few containers which are pretty heavy internet users, and having a breakout of each container's usage over time would help me make informed decisions around scheduling, uploading ratios, and bandwidth.   

I do like the check-boxes in the current version of the plugin.  Including all the veth* interfaces would be probably be the fastest way to implement this feature request.  Alternatively, having a second free form list a user could manually enter whatever interface they want could future-proof the plugin against similar requests in the future.

**Comment by dorgan** [comment]
Ok let me see about getting these added.

**Comment by dorgan** [comment]
resolved with #14
