### ISSUE TITLE
Stats not working in Version: 6.10.0-rc2

### ISSUE THREAD

**Issue by AndreBlin** [dorgan/Unraid-networkstats#16]
Hi, there is an issue in Version: 6.10.0-rc2, Stats not working.
![UnraidServerStats](https://user-images.githubusercontent.com/78139850/156549381-766fa023-0b4d-4b5a-9cdd-2cf3c20d7777.png)

**Comment by vveerar1** [comment]
Hi, I had the same problem, I got it fixed by installing the dependencies. 

When running on 6.10-rc4 you need to also see this post for further instructions: https://forums.unraid.net/topic/74525-plugin-network-stats/page/12/#comment-1105484

**Comment by dorgan** [comment]
This is fixed by not having the pretty graphs it had previously.  One of these days I'll implement a JS version of the graphs
